language: node_js
sudo: false
node_js: 5
services:
- docker
git:
  depth: 5
cache:
  pip: true
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g yarn@v0.22.0
install:
- yarn install --ignore-optional
- pip install --user -r requirements.txt
script:
- yarn run travis
env:
  global:
    secure: nbnM+8IZhRsfz2fVL9s8L9Ei7odEWqAKfetoOaMD9gn2wU4LJ/rJgyM4hpNjCjAXi9ZC3r0OldEHhuWUvDMvtfdFTOScOaIv3+pF4A37tgeoRcpOLos+QWTktImW+KEseMoTfh99m9ug1rzcBVUJ6Ik9dTnNYp8es+qMjXV1ym51OhtlxfuY57mYYL77INtdotv2rq4mlavD+LtEkoUKtMY5HlRpvlx17233bQn22AjpxtmSUbYX26XZDDeqrjfFlBPvfpx6Wzt0bajmRemBNEJ3uvZIlonvTNKD03qMs9PRhYbRcIhL8eDKkMNwJ6RbOmhV8qQm1TLxYFHpLRfX69ceYaIccimM0VH5sdlMP1pNJX2mHd+Xnsm592xCcmd8OGafH8/6YqjfFFXSREx87uAJZ5wVg9Pi9MJU31qFxWc0qtGSlS0gYVlSlOKZ/PrRTDVscicZ8L/avbZYtuo9dQ1+HRWF2WehH9r8KYmIvIviKb1VdyGVDdrMkC4ID+j9EBdr5795jkzxOev3q0ngJkaaKmKTWm5K+TBflct6IKwh8MkcoxcxVojgOpTs+fI2YxOpMbLom89+lgfHTRaRidBPnUnbQoa8lCMdPL5Ycc9yuoMHCAH0Ql5+6b/HJT/zImAoLTTGUP8RcsNcSXp0PsUruB4v+r8zWf3CID7BpVE=
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt release

